### ISSUE TITLE
Nezobrazuje poster.

### ISSUE THREAD

**Issue by Ciksa** [skyjet18/enigma2-plugin-extensions-csfd#1]
Vybavene

**Comment by skyjet18** [comment]
Zmeň v nastaveniach spôsob sťahovania dát z csfd na urlib2 (default je twistedweb). Ten twistedweb chcem vyhodiť - robí viac problémov ako úžitku ...

**Comment by Ciksa** [comment]
Uz som medzitym nato prisiel ale aj tak dakujem za promptnu odpoved.
