### ISSUE TITLE
Nefunguje prepínanie jazyka aplikácie

### ISSUE THREAD

**Issue by kostik12345** [skyjet18/enigma2-plugin-extensions-csfd#3]
Zdravím Ťa skyjet, poprosím o opravu slovenského jazyka, položky v menu pluginu sú v češtine a nastavený jazyk je slovensky. Je to vo všetkých položkách Ovládaní/ Design/ Různé... Ešte tá jedna drobnosť z logom čo som Ti poslal v SS na abfóre.
![1_0_19_3B78_C8D_3_EB0000_0_0_0](https://user-images.githubusercontent.com/74385962/148397834-f23eedf3-15db-4ad2-b909-4ae6b4ce9abb.jpg)

**Comment by skyjet18** [comment]
Opravené vo verzii 15.10
