### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by mtester270** [skyjet18/enigma2-plugin-extensions-csfd#4]
Make plugin works in both py2.7 & py3.9

**Comment by skyjet18** [comment]
Nemám prijímač s image bežiacom na python 3.x, takže to sám opraviť neviem. Pull request je vítaný ..

**Comment by skyjet18** [comment]
Prvá dávka opráv vydaná vo verzii 15.10. Na python 3.x netestované - nemám ako ...

**Comment by Ciksa** [comment]
Uz to bezi OK aj pod python3.

**Comment by skyjet18** [comment]
Pre python 3.x plugin funguje po vytvorení balíka z branchu py3. Zmeny ktoré sú v tom branchi bude potrebné postupne preniesť do mastra a hlavne ich spraviť kompatibilné s 2.7 a 3.x.

**Comment by skyjet18** [comment]
implemented in version >=16.00
